using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;

namespace Zinc.Magic
{
    /// <summary>
    /// Shader code-gen for sokol-shdc annotated .glsl files. Two halves:
    ///  - <see cref="EmitStub"/> reads the .glsl alone (no shdc) and emits the typesafe
    ///    Res.Assets.&lt;program&gt; handle plus std140 uniform structs under Res.Shaders.&lt;program&gt;.
    ///  - <see cref="EmitDesc"/> reads the shdc reflection .yaml (produced by the build target)
    ///    plus the per-stage source files and emits the runtime sg_shader factory.
    /// </summary>
    public static class ShaderGen
    {
        // ---- stub side (from .glsl, always available) ---------------------------------

        public static void EmitStub(SourceProductionContext ctx, AdditionalText glsl)
        {
            var raw = glsl.GetText(ctx.CancellationToken)?.ToString();
            if (string.IsNullOrEmpty(raw)) return;

            var src = StripComments(raw!); // so @program/@vs/@fs in comments aren't parsed as directives

            var programs = ParsePrograms(src);
            if (programs.Count == 0) return;

            var blocks = ParseUniformBlocks(src);
            var fileBase = File.SanitizeFilename(Path.GetFileNameWithoutExtension(glsl.Path));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> Zinc.Magic shader stub (handles + std140 uniform blocks)");
            sb.AppendLine();
            sb.AppendLine("namespace Res");
            sb.AppendLine("{");
            // Handle from the .glsl alone (no shdc) so you can code against a shader before building;
            // the shdc build step wires its compiled factory on via SetFactory (see EmitProgram).
            sb.AppendLine("    public static partial class Assets");
            sb.AppendLine("    {");
            foreach (var p in programs)
                sb.AppendLine($"        public static global::Zinc.Resources.Shader {p} = new(\"{p}\");");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static partial class Shaders");
            sb.AppendLine("    {");
            foreach (var p in programs)
            {
                sb.AppendLine($"        public static partial class {p}");
                sb.AppendLine("        {");
                foreach (var b in blocks)
                {
                    if (!b.Supported)
                    {
                        sb.AppendLine($"            // uniform block '{b.GlslName}' ({b.StageName}) skipped: unsupported member type for typed generation");
                        continue;
                    }
                    // std140 record struct — its [StructLayout(Size)] equals the block size, so handing
                    // its bytes to sgp_set_uniform is correct by construction.
                    sb.AppendLine($"            [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Explicit, Size = {b.Std140Size})]");
                    sb.AppendLine($"            public record struct {b.StructName}");
                    sb.AppendLine("            {");
                    foreach (var m in b.Members)
                        sb.AppendLine($"                [System.Runtime.InteropServices.FieldOffset({m.Offset})] public {m.CsType} {m.Name};");
                    sb.AppendLine("            }");
                }
                sb.AppendLine("        }");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            ctx.AddSource($"Res_{fileBase}_shader.g.cs", sb.ToString());
        }

        private static string StripComments(string src)
        {
            src = Regex.Replace(src, @"/\*.*?\*/", " ", RegexOptions.Singleline);
            src = Regex.Replace(src, @"//[^\n]*", " ");
            return src;
        }

        private static List<string> ParsePrograms(string src)
        {
            var list = new List<string>();
            foreach (Match m in Regex.Matches(src, @"@program\s+(\w+)"))
                list.Add(m.Groups[1].Value);
            return list;
        }

        private sealed class UniformBlock
        {
            public string Stage = "";       // "vs" | "fs"
            public string StageName = "";    // "vertex" | "fragment"
            public string GlslName = "";
            public string StructName = "";   // "Vs" | "Fs" (+ index if multiple)
            public int Std140Size;
            public bool Supported = true;
            public List<(string Name, string CsType, int Offset, string Glsl, int Size)> Members = new List<(string, string, int, string, int)>();
        }

        private static List<UniformBlock> ParseUniformBlocks(string src)
        {
            var (vs, fs) = ExtractStages(src);
            var blocks = new List<UniformBlock>();
            ParseStageBlocks(vs, "vs", "vertex", "Vs", blocks);
            ParseStageBlocks(fs, "fs", "fragment", "Fs", blocks);
            return blocks;
        }

        private static (string vs, string fs) ExtractStages(string src)
        {
            var lines = src.Replace("\r\n", "\n").Split('\n');
            var vs = new StringBuilder();
            var fs = new StringBuilder();
            string stage = null;
            foreach (var raw in lines)
            {
                var t = raw.TrimStart();
                if (t.StartsWith("@vs")) { stage = "vs"; continue; }
                if (t.StartsWith("@fs")) { stage = "fs"; continue; }
                if (t.StartsWith("@cs")) { stage = "cs"; continue; }
                if (t.StartsWith("@end")) { stage = null; continue; }
                if (stage == "vs") vs.AppendLine(raw);
                else if (stage == "fs") fs.AppendLine(raw);
            }
            return (vs.ToString(), fs.ToString());
        }

        private static void ParseStageBlocks(string text, string stage, string stageName, string prefix, List<UniformBlock> blocks)
        {
            var rx = new Regex(@"uniform\s+(\w+)\s*\{([^}]*)\}", RegexOptions.Singleline);
            int count = 0;
            foreach (Match m in rx.Matches(text))
            {
                var glslName = m.Groups[1].Value;
                var body = m.Groups[2].Value;
                var members = ParseMembers(body);
                var (csMembers, size, supported) = Std140.Layout(members);
                var b = new UniformBlock
                {
                    Stage = stage,
                    StageName = stageName,
                    GlslName = glslName,
                    StructName = count == 0 ? prefix : prefix + (count + 1),
                    Std140Size = size,
                    Supported = supported,
                    Members = csMembers,
                };
                blocks.Add(b);
                count++;
            }
        }

        private static List<(string type, string name, int arr)> ParseMembers(string body)
        {
            var members = new List<(string, string, int)>();
            foreach (var rawLine in body.Split(';'))
            {
                // strip line comments
                var line = rawLine;
                var ci = line.IndexOf("//", StringComparison.Ordinal);
                if (ci >= 0) line = line.Substring(0, ci);
                line = line.Trim();
                if (line.Length == 0) continue;
                var mm = Regex.Match(line, @"^(\w+)\s+(\w+)\s*(\[\s*(\d+)\s*\])?$");
                if (!mm.Success) continue;
                int arr = mm.Groups[4].Success ? int.Parse(mm.Groups[4].Value) : 0;
                members.Add((mm.Groups[1].Value, mm.Groups[2].Value, arr));
            }
            return members;
        }

        // ---- desc side (from shdc reflection .yaml + sources) -------------------------

        public static void EmitDesc(SourceProductionContext ctx, AdditionalText yamlFile, ImmutableArray<AdditionalText> allFiles)
        {
            var yamlText = yamlFile.GetText(ctx.CancellationToken)?.ToString();
            if (string.IsNullOrEmpty(yamlText)) return;

            object root;
            try { root = MiniYaml.Parse(yamlText!); }
            catch { return; }

            if (!(root is Dictionary<string, object> rootMap)) return;
            if (!(GetVal(rootMap, "shaders") is List<object> shaders)) return;

            // shdc with multiple `-l` slangs in one invocation produces a single reflection.yaml whose
            // top-level `shaders:` list has one entry per slang (each carrying its own per-stage source
            // paths and slang-specific register fields). Emit a separate factory file per (program, slang)
            // pair so each registers itself under the matching sg_backend at module load.
            foreach (var shObj in shaders)
            {
                if (!(shObj is Dictionary<string, object> sh)) continue;
                if (!(GetVal(sh, "slang") is string slang)) continue;
                var binding = SlangBindings.For(slang);
                if (binding == null) continue; // unknown slang — skip rather than emit broken code
                if (!(GetVal(sh, "programs") is List<object> programs)) continue;
                foreach (var pObj in programs)
                {
                    if (pObj is Dictionary<string, object> p)
                        EmitProgram(ctx, p, allFiles, slang, binding);
                }
            }
        }

        /// <summary>
        /// Per-slang naming conventions in shdc's reflection. Captures (a) the runtime sg_backend
        /// the slang targets, (b) the YAML field giving each uniform-block / texture / sampler its
        /// backend-specific register slot, and (c) whether texture_sampler_pairs need glsl_name set
        /// (sokol validates that on GL backends; Metal/D3D11 ignore it).
        /// </summary>
        private sealed class SlangBinding
        {
            public string Backend = "";          // sg_backend enum const
            public string UbRegisterField = "";   // yaml key for uniform-block register slot per backend
            public string TexRegisterField = "";  // yaml key for texture register slot
            public string SmpRegisterField = "";  // yaml key for sampler register slot
            public string DescField = "";         // sg_shader_desc field name (msl_buffer_n / hlsl_register_b_n / ...)
            public string DescTexField = "";
            public string DescSmpField = "";
            public bool PairsNeedGlslName;        // emit texture_sampler_pairs[i].glsl_name?
        }

        private static class SlangBindings
        {
            public static SlangBinding For(string slang)
            {
                switch (slang)
                {
                    case "metal_macos": return Metal("SG_BACKEND_METAL_MACOS");
                    case "metal_ios":   return Metal("SG_BACKEND_METAL_IOS");
                    case "metal_sim":   return Metal("SG_BACKEND_METAL_SIMULATOR");
                    case "hlsl4":
                    case "hlsl5":       return Hlsl();
                    case "glsl410":
                    case "glsl430":     return Glsl("SG_BACKEND_GLCORE");
                    case "glsl300es":
                    case "glsl310es":   return Glsl("SG_BACKEND_GLES3");
                    case "wgsl":        return Wgsl();
                    default: return null;
                }
            }

            // Metal: the buffer/texture/sampler index in MSL is the yaml's msl_*_n field, mapped to
            // sg_shader_desc.{uniform_blocks,views.texture,samplers}.msl_*_n. Texture-sampler pairs
            // exist on Metal but don't need a name (Metal binds texture+sampler independently).
            private static SlangBinding Metal(string backend) => new SlangBinding {
                Backend = backend,
                UbRegisterField = "msl_buffer_n",  TexRegisterField = "msl_texture_n", SmpRegisterField = "msl_sampler_n",
                DescField = "msl_buffer_n",        DescTexField = "msl_texture_n",     DescSmpField = "msl_sampler_n",
                PairsNeedGlslName = false,
            };

            // HLSL5/D3D11: hlsl_register_{b,t,s}_n give the cbuffer / SRV / sampler register indices,
            // which sg_shader_desc surfaces as hlsl_register_{b,t,s}_n on the same structures.
            private static SlangBinding Hlsl() => new SlangBinding {
                Backend = "SG_BACKEND_D3D11",
                UbRegisterField = "hlsl_register_b_n", TexRegisterField = "hlsl_register_t_n", SmpRegisterField = "hlsl_register_s_n",
                DescField = "hlsl_register_b_n",       DescTexField = "hlsl_register_t_n",     DescSmpField = "hlsl_register_s_n",
                PairsNeedGlslName = false,
            };

            // GL: no per-backend register field on uniform_blocks / views / samplers (sokol_gfx uses
            // `slot` directly). texture_sampler_pairs DO need glsl_name — sokol validates it on GL —
            // and the yaml conveniently provides it on each pair entry.
            private static SlangBinding Glsl(string backend) => new SlangBinding {
                Backend = backend,
                UbRegisterField = null, TexRegisterField = null, SmpRegisterField = null,
                DescField = null,       DescTexField = null,     DescSmpField = null,
                PairsNeedGlslName = true,
            };

            // WebGPU shares structure with HLSL/Metal for these knobs but uses wgsl_group{0,1}_binding_n.
            // We don't have a Zinc-side WGPU runtime yet; emit the file so the slang isn't broken if
            // someone toggles it on, but it won't be reachable until Engine boots with a wgpu backend.
            private static SlangBinding Wgsl() => new SlangBinding {
                Backend = "SG_BACKEND_WGPU",
                UbRegisterField = "wgsl_group0_binding_n", TexRegisterField = "wgsl_group1_binding_n", SmpRegisterField = "wgsl_group1_binding_n",
                DescField = "wgsl_group0_binding_n",       DescTexField = "wgsl_group1_binding_n",     DescSmpField = "wgsl_group1_binding_n",
                PairsNeedGlslName = false,
            };
        }

        private static void EmitProgram(SourceProductionContext ctx, Dictionary<string, object> p, ImmutableArray<AdditionalText> allFiles, string slang, SlangBinding binding)
        {
            if (!(GetVal(p, "name") is string name)) return;
            var vf = GetVal(p, "vertex_func") as Dictionary<string, object>;
            var ff = GetVal(p, "fragment_func") as Dictionary<string, object>;
            if (vf == null || ff == null) return;

            var vsSrc = FindContent(allFiles, GetVal(vf, "path") as string, ctx);
            var fsSrc = FindContent(allFiles, GetVal(ff, "path") as string, ctx);
            if (vsSrc == null || fsSrc == null) return; // per-stage sources not present yet (pre-build)

            // Metal's MSL entry point is "main0" (SPIRV-Cross's default rename); HLSL & GLSL both use
            // plain "main". We trust whatever the reflection yaml says rather than hardcoding here.
            var vsEntry = GetVal(vf, "entry_point") as string ?? "main";
            var fsEntry = GetVal(ff, "entry_point") as string ?? "main";
            var vsB64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(vsSrc));
            var fsB64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(fsSrc));

            // Pinning plan: every C-string we hand to sokol (the source code, entry-point names, plus
            // HLSL semantic names and GL sampler-pair names) must point at memory the GC can't move
            // for the duration of the `Gfx.make_shader` call. We collect all pinnables first, emit
            // them as static byte[] fields, then open ONE nested `fixed(...)` chain at the top of
            // Make() so every pointer in `sg_shader_desc` is valid through the whole call. Trying
            // to pin per-statement is wrong: the pointer becomes dangling the instant the `fixed`
            // statement ends, and sg_make_shader doesn't read until later.
            var pinnables = new List<(string Field, string Bytes)>
            {
                ("_vs", $"Dec(\"{vsB64}\")"),
                ("_fs", $"Dec(\"{fsB64}\")"),
                ("_ve", $"Ent(\"{vsEntry}\")"),
                ("_fe", $"Ent(\"{fsEntry}\")"),
            };
            // (field, pointer-var) tuples emitted into the body to wire each pinned pointer onto
            // the sg_shader_desc field that needs it.
            var bodyLines = new List<string>();
            bodyLines.Add("                sg_shader_desc d = default;");
            bodyLines.Add("                d.vertex_func.source = (sbyte*)_vsP;");
            bodyLines.Add("                d.vertex_func.entry = (sbyte*)_veP;");
            bodyLines.Add("                d.fragment_func.source = (sbyte*)_fsP;");
            bodyLines.Add("                d.fragment_func.entry = (sbyte*)_feP;");

            if (GetVal(p, "attrs") is List<object> attrs)
            {
                foreach (var aObj in attrs)
                {
                    if (!(aObj is Dictionary<string, object> a)) continue;
                    var slot = GetVal(a, "slot") as string ?? "0";
                    var bt = (GetVal(a, "base_type") as string) ?? "Float";
                    bodyLines.Add($"                d.attrs[{slot}].base_type = sg_shader_attr_base_type.{AttrBaseType(bt)};");
                    // HLSL needs the input-layout's semantic name + index (so it matches the
                    // signature baked into the compiled shader bytecode). Metal/GL/WGPU ignore it.
                    if (slang == "hlsl4" || slang == "hlsl5")
                    {
                        var sem = GetVal(a, "hlsl_sem_name") as string;
                        var idx = GetVal(a, "hlsl_sem_index") as string ?? "0";
                        if (!string.IsNullOrEmpty(sem))
                        {
                            var field = $"_aSem{slot}";
                            pinnables.Add((field, $"Ent(\"{sem}\")"));
                            bodyLines.Add($"                d.attrs[{slot}].hlsl_sem_name = (sbyte*){field}P;");
                            bodyLines.Add($"                d.attrs[{slot}].hlsl_sem_index = {idx};");
                        }
                    }
                }
            }

            if (GetVal(p, "uniform_blocks") is List<object> ubs)
            {
                foreach (var uObj in ubs)
                {
                    if (!(uObj is Dictionary<string, object> u)) continue;
                    var slot = GetVal(u, "slot") as string ?? "0";
                    var stage = GetVal(u, "stage") as string ?? "fragment";
                    var size = GetVal(u, "size") as string ?? "0";
                    bodyLines.Add($"                d.uniform_blocks[{slot}].stage = sg_shader_stage.{Stage(stage)};");
                    bodyLines.Add($"                d.uniform_blocks[{slot}].layout = sg_uniform_layout.SG_UNIFORMLAYOUT_STD140;");
                    bodyLines.Add($"                d.uniform_blocks[{slot}].size = {size};");
                    if (binding.DescField != null)
                    {
                        var reg = GetVal(u, binding.UbRegisterField) as string ?? slot;
                        bodyLines.Add($"                d.uniform_blocks[{slot}].{binding.DescField} = {reg};");
                    }
                }
            }

            // Sampled textures. Reflection nests each under a `texture:` key (the other view kinds
            // are storage_buffer/storage_image, which sgp shaders don't use).
            if (GetVal(p, "views") is List<object> views)
            {
                foreach (var vObj in views)
                {
                    if (!(vObj is Dictionary<string, object> v)) continue;
                    if (!(GetVal(v, "texture") is Dictionary<string, object> t)) continue;
                    var slot = GetVal(t, "slot") as string ?? "0";
                    var stage = GetVal(t, "stage") as string ?? "fragment";
                    var imgType = GetVal(t, "type") as string ?? "2d";
                    var sampleType = GetVal(t, "sample_type") as string ?? "float";
                    var multisampled = string.Equals(GetVal(t, "multisampled") as string, "true", StringComparison.OrdinalIgnoreCase);
                    bodyLines.Add($"                d.views[{slot}].texture.stage = sg_shader_stage.{Stage(stage)};");
                    bodyLines.Add($"                d.views[{slot}].texture.image_type = sg_image_type.{ImageType(imgType)};");
                    bodyLines.Add($"                d.views[{slot}].texture.sample_type = sg_image_sample_type.{SampleType(sampleType)};");
                    bodyLines.Add($"                d.views[{slot}].texture.multisampled = {(multisampled ? "1" : "0")};");
                    if (binding.DescTexField != null)
                    {
                        var reg = GetVal(t, binding.TexRegisterField) as string ?? slot;
                        bodyLines.Add($"                d.views[{slot}].texture.{binding.DescTexField} = {reg};");
                    }
                }
            }

            if (GetVal(p, "samplers") is List<object> samplers)
            {
                foreach (var sObj in samplers)
                {
                    if (!(sObj is Dictionary<string, object> s)) continue;
                    var slot = GetVal(s, "slot") as string ?? "0";
                    var stage = GetVal(s, "stage") as string ?? "fragment";
                    var smpType = GetVal(s, "sampler_type") as string ?? "filtering";
                    bodyLines.Add($"                d.samplers[{slot}].stage = sg_shader_stage.{Stage(stage)};");
                    bodyLines.Add($"                d.samplers[{slot}].sampler_type = sg_sampler_type.{SamplerType(smpType)};");
                    if (binding.DescSmpField != null)
                    {
                        var reg = GetVal(s, binding.SmpRegisterField) as string ?? slot;
                        bodyLines.Add($"                d.samplers[{slot}].{binding.DescSmpField} = {reg};");
                    }
                }
            }

            // Every texture view must be referenced by a texture-sampler pair (sokol validation).
            // glsl_name is required on GL backends so the linker can match the sampler to its
            // declaration in the generated GLSL; Metal/D3D11 ignore it (the pair is bound positionally).
            if (GetVal(p, "texture_sampler_pairs") is List<object> pairs)
            {
                foreach (var prObj in pairs)
                {
                    if (!(prObj is Dictionary<string, object> pr)) continue;
                    var slot = GetVal(pr, "slot") as string ?? "0";
                    var stage = GetVal(pr, "stage") as string ?? "fragment";
                    var viewSlot = GetVal(pr, "view_slot") as string ?? "0";
                    var smpSlot = GetVal(pr, "sampler_slot") as string ?? "0";
                    bodyLines.Add($"                d.texture_sampler_pairs[{slot}].stage = sg_shader_stage.{Stage(stage)};");
                    bodyLines.Add($"                d.texture_sampler_pairs[{slot}].view_slot = {viewSlot};");
                    bodyLines.Add($"                d.texture_sampler_pairs[{slot}].sampler_slot = {smpSlot};");
                    if (binding.PairsNeedGlslName)
                    {
                        var glslName = GetVal(pr, "glsl_name") as string;
                        if (!string.IsNullOrEmpty(glslName))
                        {
                            var field = $"_pName{slot}";
                            pinnables.Add((field, $"Ent(\"{glslName}\")"));
                            bodyLines.Add($"                d.texture_sampler_pairs[{slot}].glsl_name = (sbyte*){field}P;");
                        }
                    }
                }
            }

            // Stitch it together: static byte[] fields, the Make() prelude, one big nested fixed
            // chain over every pinnable, then the body, then make_shader.
            var sb = new StringBuilder();
            sb.AppendLine($"// <auto-generated/> Zinc.Magic compiled shader ({slang})");
            sb.AppendLine("using System;");
            sb.AppendLine("using Zinc.Internal.Sokol;");
            sb.AppendLine("namespace Res.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    internal static class Shader_{name}__{slang}");
            sb.AppendLine("    {");
            sb.AppendLine("        [System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine($"        internal static void Init() => global::Res.Assets.{name}.RegisterFactory(sg_backend.{binding.Backend}, Make);");
            foreach (var (field, init) in pinnables)
                sb.AppendLine($"        static readonly byte[] {field} = {init};");
            sb.AppendLine("        static byte[] Dec(string b){ var s = Convert.FromBase64String(b); var r = new byte[s.Length + 1]; Array.Copy(s, r, s.Length); return r; }");
            sb.AppendLine("        static byte[] Ent(string s){ var b = System.Text.Encoding.ASCII.GetBytes(s); var r = new byte[b.Length + 1]; Array.Copy(b, r, b.Length); return r; }");
            sb.AppendLine("        internal static unsafe sg_shader Make(sg_backend backend)");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (backend != sg_backend.{binding.Backend})");
            sb.AppendLine($"                throw new NotSupportedException(\"Shader '{name}' was compiled for {slang} ({binding.Backend}); runtime backend \" + backend + \" is a mismatch — check RegisterFactory wiring.\");");
            // One big nested fixed-chain: every pinnable byte[] => its `*P` pointer. C# allows
            // adjacent `fixed(...)` clauses with no `{}` between them as a stacked form, all in
            // scope for the single body block that follows.
            foreach (var (field, _) in pinnables)
                sb.AppendLine($"            fixed (byte* {field}P = {field})");
            sb.AppendLine("            {");
            foreach (var line in bodyLines)
                sb.AppendLine(line);
            sb.AppendLine("                return Gfx.make_shader(&d);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            ctx.AddSource($"Shader_{name}__{slang}.g.cs", sb.ToString());
        }

        private static string AttrBaseType(string s)
        {
            switch (s)
            {
                case "SInt": return "SG_SHADERATTRBASETYPE_SINT";
                case "UInt": return "SG_SHADERATTRBASETYPE_UINT";
                default: return "SG_SHADERATTRBASETYPE_FLOAT";
            }
        }

        private static string Stage(string s)
        {
            switch (s)
            {
                case "vertex": return "SG_SHADERSTAGE_VERTEX";
                case "compute": return "SG_SHADERSTAGE_COMPUTE";
                default: return "SG_SHADERSTAGE_FRAGMENT";
            }
        }

        private static string ImageType(string s)
        {
            switch (s)
            {
                case "cube": return "SG_IMAGETYPE_CUBE";
                case "3d": return "SG_IMAGETYPE_3D";
                case "array": return "SG_IMAGETYPE_ARRAY";
                default: return "SG_IMAGETYPE_2D";
            }
        }

        private static string SampleType(string s)
        {
            switch (s)
            {
                case "depth": return "SG_IMAGESAMPLETYPE_DEPTH";
                case "sint": return "SG_IMAGESAMPLETYPE_SINT";
                case "uint": return "SG_IMAGESAMPLETYPE_UINT";
                case "unfilterable_float": return "SG_IMAGESAMPLETYPE_UNFILTERABLE_FLOAT";
                default: return "SG_IMAGESAMPLETYPE_FLOAT";
            }
        }

        private static string SamplerType(string s)
        {
            switch (s)
            {
                case "nonfiltering": return "SG_SAMPLERTYPE_NONFILTERING";
                case "comparison": return "SG_SAMPLERTYPE_COMPARISON";
                default: return "SG_SAMPLERTYPE_FILTERING";
            }
        }

        private static object GetVal(Dictionary<string, object> map, string key)
            => map != null && map.TryGetValue(key, out var v) ? v : null;

        private static string FindContent(ImmutableArray<AdditionalText> files, string pathFromYaml, SourceProductionContext ctx)
        {
            if (string.IsNullOrEmpty(pathFromYaml)) return null;
            var fn = Path.GetFileName(pathFromYaml);
            foreach (var f in files)
                if (string.Equals(Path.GetFileName(f.Path), fn, StringComparison.OrdinalIgnoreCase))
                    return f.GetText(ctx.CancellationToken)?.ToString();
            return null;
        }
    }

    /// <summary>std140 layout for the GLSL scalar/vector/mat4 types used by sgp shaders.</summary>
    internal static class Std140
    {
        public static (List<(string Name, string CsType, int Offset, string Glsl, int Size)> members, int size, bool supported) Layout(
            List<(string type, string name, int arr)> members)
        {
            var outm = new List<(string, string, int, string, int)>();
            int offset = 0;
            foreach (var (type, name, arr) in members)
            {
                if (arr > 0) return (outm, 0, false); // arrays unsupported in v1
                if (!Map(type, out var cs, out var sz, out var al, out var glsl)) return (outm, 0, false);
                offset = Align(offset, al);
                outm.Add((name, cs, offset, glsl, sz));
                offset += sz;
            }
            return (outm, Align(offset, 16), true);
        }

        // cs = C# type for the typed struct; glsl = Zinc.GlslType enum name; size = data bytes; align = std140 alignment.
        private static bool Map(string type, out string cs, out int size, out int align, out string glsl)
        {
            switch (type)
            {
                case "float": cs = "float"; size = 4; align = 4; glsl = "Float"; return true;
                case "int": cs = "int"; size = 4; align = 4; glsl = "Int"; return true;
                case "uint": cs = "uint"; size = 4; align = 4; glsl = "UInt"; return true;
                case "bool": cs = "int"; size = 4; align = 4; glsl = "Int"; return true;
                case "vec2": cs = "global::System.Numerics.Vector2"; size = 8; align = 8; glsl = "Vec2"; return true;
                case "vec3": cs = "global::System.Numerics.Vector3"; size = 12; align = 16; glsl = "Vec3"; return true;
                case "vec4": cs = "global::System.Numerics.Vector4"; size = 16; align = 16; glsl = "Vec4"; return true;
                case "mat4":
                case "mat4x4": cs = "global::System.Numerics.Matrix4x4"; size = 64; align = 16; glsl = "Mat4"; return true;
                default: cs = null; size = 0; align = 0; glsl = null; return false;
            }
        }

        private static int Align(int x, int a) => ((x + a - 1) / a) * a;
    }

    /// <summary>
    /// Minimal parser for the fixed, block-style YAML sokol-shdc emits (--format bare_yaml).
    /// Sequence items are always a lone "-" with deeper children; mappings are "key: value"
    /// or "key:" + a deeper block. Not a general YAML implementation.
    /// </summary>
    internal static class MiniYaml
    {
        public static object Parse(string text)
        {
            var lines = new List<(int indent, string content)>();
            foreach (var raw in text.Replace("\r\n", "\n").Split('\n'))
            {
                if (string.IsNullOrWhiteSpace(raw)) continue;
                var trimmed = raw.TrimStart(' ');
                if (trimmed.StartsWith("#")) continue;
                lines.Add((raw.Length - trimmed.Length, trimmed.TrimEnd()));
            }
            int idx = 0;
            if (lines.Count == 0) return null;
            return ParseBlock(lines, ref idx, lines[0].indent);
        }

        private static object ParseBlock(List<(int indent, string content)> lines, ref int idx, int curIndent)
        {
            if (idx >= lines.Count) return null;
            return lines[idx].content == "-"
                ? (object)ParseSeq(lines, ref idx, curIndent)
                : ParseMap(lines, ref idx, curIndent);
        }

        private static List<object> ParseSeq(List<(int indent, string content)> lines, ref int idx, int curIndent)
        {
            var list = new List<object>();
            while (idx < lines.Count && lines[idx].indent == curIndent && lines[idx].content == "-")
            {
                idx++; // consume the "-"
                if (idx < lines.Count && lines[idx].indent > curIndent)
                    list.Add(ParseBlock(lines, ref idx, lines[idx].indent));
                else
                    list.Add(null);
            }
            return list;
        }

        private static Dictionary<string, object> ParseMap(List<(int indent, string content)> lines, ref int idx, int curIndent)
        {
            var map = new Dictionary<string, object>();
            while (idx < lines.Count && lines[idx].indent == curIndent && lines[idx].content != "-")
            {
                var line = lines[idx].content;
                int colon = line.IndexOf(':');
                if (colon < 0) { idx++; continue; }
                var key = line.Substring(0, colon).Trim();
                var val = line.Substring(colon + 1).Trim();
                idx++;
                if (val.Length > 0)
                    map[key] = val;
                else if (idx < lines.Count && lines[idx].indent > curIndent)
                    map[key] = ParseBlock(lines, ref idx, lines[idx].indent);
                else
                    map[key] = null;
            }
            return map;
        }
    }
}
