using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;

namespace Zinc.Magic
{
    /// <summary>
    /// Shader code-gen for sokol-shdc annotated .glsl files. Two halves:
    ///  - <see cref="EmitStub"/> reads the .glsl alone (no shdc) and emits the typesafe
    ///    Res.Assets.&lt;program&gt; handle plus std140 uniform structs under Res.Shaders.&lt;program&gt;.
    ///  - <see cref="EmitDesc"/> reads the shdc reflection .yaml (produced by the build target)
    ///    plus the per-stage source files and emits the runtime sg_shader factory.
    /// </summary>
    public static class ShaderGen
    {
        // ---- stub side (from .glsl, always available) ---------------------------------

        public static void EmitStub(SourceProductionContext ctx, AdditionalText glsl)
        {
            var raw = glsl.GetText(ctx.CancellationToken)?.ToString();
            if (string.IsNullOrEmpty(raw)) return;

            var src = StripComments(raw!); // so @program/@vs/@fs in comments aren't parsed as directives

            var programs = ParsePrograms(src);
            if (programs.Count == 0) return;

            var blocks = ParseUniformBlocks(src);
            var fileBase = File.SanitizeFilename(Path.GetFileNameWithoutExtension(glsl.Path));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> Zinc.Magic shader stub (handles + std140 uniform blocks)");
            sb.AppendLine();
            sb.AppendLine("namespace Res");
            sb.AppendLine("{");
            // Handle from the .glsl alone (no shdc) so you can code against a shader before building;
            // the shdc build step wires its compiled factory on via SetFactory (see EmitProgram).
            sb.AppendLine("    public static partial class Assets");
            sb.AppendLine("    {");
            foreach (var p in programs)
                sb.AppendLine($"        public static global::Zinc.Resources.Shader {p} = new(\"{p}\");");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static partial class Shaders");
            sb.AppendLine("    {");
            foreach (var p in programs)
            {
                sb.AppendLine($"        public static partial class {p}");
                sb.AppendLine("        {");
                foreach (var b in blocks)
                {
                    if (!b.Supported)
                    {
                        sb.AppendLine($"            // uniform block '{b.GlslName}' ({b.StageName}) skipped: unsupported member type for typed generation");
                        continue;
                    }
                    // std140 record struct — its [StructLayout(Size)] equals the block size, so handing
                    // its bytes to sgp_set_uniform is correct by construction.
                    sb.AppendLine($"            [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Explicit, Size = {b.Std140Size})]");
                    sb.AppendLine($"            public record struct {b.StructName}");
                    sb.AppendLine("            {");
                    foreach (var m in b.Members)
                        sb.AppendLine($"                [System.Runtime.InteropServices.FieldOffset({m.Offset})] public {m.CsType} {m.Name};");
                    sb.AppendLine("            }");
                }
                sb.AppendLine("        }");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            ctx.AddSource($"Res_{fileBase}_shader.g.cs", sb.ToString());
        }

        private static string StripComments(string src)
        {
            src = Regex.Replace(src, @"/\*.*?\*/", " ", RegexOptions.Singleline);
            src = Regex.Replace(src, @"//[^\n]*", " ");
            return src;
        }

        private static List<string> ParsePrograms(string src)
        {
            var list = new List<string>();
            foreach (Match m in Regex.Matches(src, @"@program\s+(\w+)"))
                list.Add(m.Groups[1].Value);
            return list;
        }

        private sealed class UniformBlock
        {
            public string Stage = "";       // "vs" | "fs"
            public string StageName = "";    // "vertex" | "fragment"
            public string GlslName = "";
            public string StructName = "";   // "Vs" | "Fs" (+ index if multiple)
            public int Std140Size;
            public bool Supported = true;
            public List<(string Name, string CsType, int Offset, string Glsl, int Size)> Members = new List<(string, string, int, string, int)>();
        }

        private static List<UniformBlock> ParseUniformBlocks(string src)
        {
            var (vs, fs) = ExtractStages(src);
            var blocks = new List<UniformBlock>();
            ParseStageBlocks(vs, "vs", "vertex", "Vs", blocks);
            ParseStageBlocks(fs, "fs", "fragment", "Fs", blocks);
            return blocks;
        }

        private static (string vs, string fs) ExtractStages(string src)
        {
            var lines = src.Replace("\r\n", "\n").Split('\n');
            var vs = new StringBuilder();
            var fs = new StringBuilder();
            string stage = null;
            foreach (var raw in lines)
            {
                var t = raw.TrimStart();
                if (t.StartsWith("@vs")) { stage = "vs"; continue; }
                if (t.StartsWith("@fs")) { stage = "fs"; continue; }
                if (t.StartsWith("@cs")) { stage = "cs"; continue; }
                if (t.StartsWith("@end")) { stage = null; continue; }
                if (stage == "vs") vs.AppendLine(raw);
                else if (stage == "fs") fs.AppendLine(raw);
            }
            return (vs.ToString(), fs.ToString());
        }

        private static void ParseStageBlocks(string text, string stage, string stageName, string prefix, List<UniformBlock> blocks)
        {
            var rx = new Regex(@"uniform\s+(\w+)\s*\{([^}]*)\}", RegexOptions.Singleline);
            int count = 0;
            foreach (Match m in rx.Matches(text))
            {
                var glslName = m.Groups[1].Value;
                var body = m.Groups[2].Value;
                var members = ParseMembers(body);
                var (csMembers, size, supported) = Std140.Layout(members);
                var b = new UniformBlock
                {
                    Stage = stage,
                    StageName = stageName,
                    GlslName = glslName,
                    StructName = count == 0 ? prefix : prefix + (count + 1),
                    Std140Size = size,
                    Supported = supported,
                    Members = csMembers,
                };
                blocks.Add(b);
                count++;
            }
        }

        private static List<(string type, string name, int arr)> ParseMembers(string body)
        {
            var members = new List<(string, string, int)>();
            foreach (var rawLine in body.Split(';'))
            {
                // strip line comments
                var line = rawLine;
                var ci = line.IndexOf("//", StringComparison.Ordinal);
                if (ci >= 0) line = line.Substring(0, ci);
                line = line.Trim();
                if (line.Length == 0) continue;
                var mm = Regex.Match(line, @"^(\w+)\s+(\w+)\s*(\[\s*(\d+)\s*\])?$");
                if (!mm.Success) continue;
                int arr = mm.Groups[4].Success ? int.Parse(mm.Groups[4].Value) : 0;
                members.Add((mm.Groups[1].Value, mm.Groups[2].Value, arr));
            }
            return members;
        }

        // ---- desc side (from shdc reflection .yaml + sources) -------------------------

        public static void EmitDesc(SourceProductionContext ctx, AdditionalText yamlFile, ImmutableArray<AdditionalText> allFiles)
        {
            var yamlText = yamlFile.GetText(ctx.CancellationToken)?.ToString();
            if (string.IsNullOrEmpty(yamlText)) return;

            object root;
            try { root = MiniYaml.Parse(yamlText!); }
            catch { return; }

            if (!(root is Dictionary<string, object> rootMap)) return;
            if (!(GetVal(rootMap, "shaders") is List<object> shaders)) return;

            foreach (var shObj in shaders)
            {
                if (!(shObj is Dictionary<string, object> sh)) continue;
                if (!(GetVal(sh, "slang") is string slang)) continue;
                if (slang != "metal_macos") continue; // v1: Metal only
                if (!(GetVal(sh, "programs") is List<object> programs)) continue;
                foreach (var pObj in programs)
                {
                    if (pObj is Dictionary<string, object> p)
                        EmitProgram(ctx, p, allFiles);
                }
            }
        }

        private static void EmitProgram(SourceProductionContext ctx, Dictionary<string, object> p, ImmutableArray<AdditionalText> allFiles)
        {
            if (!(GetVal(p, "name") is string name)) return;
            var vf = GetVal(p, "vertex_func") as Dictionary<string, object>;
            var ff = GetVal(p, "fragment_func") as Dictionary<string, object>;
            if (vf == null || ff == null) return;

            var vsSrc = FindContent(allFiles, GetVal(vf, "path") as string, ctx);
            var fsSrc = FindContent(allFiles, GetVal(ff, "path") as string, ctx);
            if (vsSrc == null || fsSrc == null) return; // metal sources not present yet (pre-build)

            var vsEntry = GetVal(vf, "entry_point") as string ?? "main0";
            var fsEntry = GetVal(ff, "entry_point") as string ?? "main0";
            var vsB64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(vsSrc));
            var fsB64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(fsSrc));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> Zinc.Magic compiled shader (metal_macos)");
            sb.AppendLine("using System;");
            sb.AppendLine("using Zinc.Internal.Sokol;");
            sb.AppendLine("namespace Res.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    internal static class Shader_{name}__metal_macos");
            sb.AppendLine("    {");
            sb.AppendLine("        [System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine($"        internal static void Init() => global::Res.Assets.{name}.SetFactory(Make);");
            sb.AppendLine($"        static readonly byte[] _vs = Dec(\"{vsB64}\");");
            sb.AppendLine($"        static readonly byte[] _fs = Dec(\"{fsB64}\");");
            sb.AppendLine($"        static readonly byte[] _ve = Ent(\"{vsEntry}\");");
            sb.AppendLine($"        static readonly byte[] _fe = Ent(\"{fsEntry}\");");
            sb.AppendLine("        static byte[] Dec(string b){ var s = Convert.FromBase64String(b); var r = new byte[s.Length + 1]; Array.Copy(s, r, s.Length); return r; }");
            sb.AppendLine("        static byte[] Ent(string s){ var b = System.Text.Encoding.ASCII.GetBytes(s); var r = new byte[b.Length + 1]; Array.Copy(b, r, b.Length); return r; }");
            sb.AppendLine("        internal static unsafe sg_shader Make(sg_backend backend)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (backend != sg_backend.SG_BACKEND_METAL_MACOS)");
            sb.AppendLine($"                throw new NotSupportedException(\"Shader '{name}' was only compiled for Metal (macOS); backend \" + backend + \" is unsupported.\");");
            sb.AppendLine("            fixed (byte* vs = _vs) fixed (byte* fs = _fs) fixed (byte* ve = _ve) fixed (byte* fe = _fe)");
            sb.AppendLine("            {");
            sb.AppendLine("                sg_shader_desc d = default;");
            sb.AppendLine("                d.vertex_func.source = (sbyte*)vs;");
            sb.AppendLine("                d.vertex_func.entry = (sbyte*)ve;");
            sb.AppendLine("                d.fragment_func.source = (sbyte*)fs;");
            sb.AppendLine("                d.fragment_func.entry = (sbyte*)fe;");

            if (GetVal(p, "attrs") is List<object> attrs)
            {
                foreach (var aObj in attrs)
                {
                    if (!(aObj is Dictionary<string, object> a)) continue;
                    var slot = GetVal(a, "slot") as string ?? "0";
                    var bt = (GetVal(a, "base_type") as string) ?? "Float";
                    sb.AppendLine($"                d.attrs[{slot}].base_type = sg_shader_attr_base_type.{AttrBaseType(bt)};");
                }
            }

            if (GetVal(p, "uniform_blocks") is List<object> ubs)
            {
                foreach (var uObj in ubs)
                {
                    if (!(uObj is Dictionary<string, object> u)) continue;
                    var slot = GetVal(u, "slot") as string ?? "0";
                    var stage = GetVal(u, "stage") as string ?? "fragment";
                    var size = GetVal(u, "size") as string ?? "0";
                    var msl = GetVal(u, "msl_buffer_n") as string ?? slot;
                    sb.AppendLine($"                d.uniform_blocks[{slot}].stage = sg_shader_stage.{Stage(stage)};");
                    sb.AppendLine($"                d.uniform_blocks[{slot}].layout = sg_uniform_layout.SG_UNIFORMLAYOUT_STD140;");
                    sb.AppendLine($"                d.uniform_blocks[{slot}].size = {size};");
                    sb.AppendLine($"                d.uniform_blocks[{slot}].msl_buffer_n = {msl};");
                }
            }

            // Sampled textures. Reflection nests each under a `texture:` key (the other view kinds
            // are storage_buffer/storage_image, which sgp shaders don't use).
            if (GetVal(p, "views") is List<object> views)
            {
                foreach (var vObj in views)
                {
                    if (!(vObj is Dictionary<string, object> v)) continue;
                    if (!(GetVal(v, "texture") is Dictionary<string, object> t)) continue;
                    var slot = GetVal(t, "slot") as string ?? "0";
                    var stage = GetVal(t, "stage") as string ?? "fragment";
                    var imgType = GetVal(t, "type") as string ?? "2d";
                    var sampleType = GetVal(t, "sample_type") as string ?? "float";
                    var multisampled = string.Equals(GetVal(t, "multisampled") as string, "true", StringComparison.OrdinalIgnoreCase);
                    var mslTex = GetVal(t, "msl_texture_n") as string ?? slot;
                    sb.AppendLine($"                d.views[{slot}].texture.stage = sg_shader_stage.{Stage(stage)};");
                    sb.AppendLine($"                d.views[{slot}].texture.image_type = sg_image_type.{ImageType(imgType)};");
                    sb.AppendLine($"                d.views[{slot}].texture.sample_type = sg_image_sample_type.{SampleType(sampleType)};");
                    sb.AppendLine($"                d.views[{slot}].texture.multisampled = {(multisampled ? "1" : "0")};");
                    sb.AppendLine($"                d.views[{slot}].texture.msl_texture_n = {mslTex};");
                }
            }

            if (GetVal(p, "samplers") is List<object> samplers)
            {
                foreach (var sObj in samplers)
                {
                    if (!(sObj is Dictionary<string, object> s)) continue;
                    var slot = GetVal(s, "slot") as string ?? "0";
                    var stage = GetVal(s, "stage") as string ?? "fragment";
                    var smpType = GetVal(s, "sampler_type") as string ?? "filtering";
                    var mslSmp = GetVal(s, "msl_sampler_n") as string ?? slot;
                    sb.AppendLine($"                d.samplers[{slot}].stage = sg_shader_stage.{Stage(stage)};");
                    sb.AppendLine($"                d.samplers[{slot}].sampler_type = sg_sampler_type.{SamplerType(smpType)};");
                    sb.AppendLine($"                d.samplers[{slot}].msl_sampler_n = {mslSmp};");
                }
            }

            // Every texture view must be referenced by a texture-sampler pair (sokol validation);
            // glsl_name is only required on GL backends, so it's omitted for metal_macos.
            if (GetVal(p, "texture_sampler_pairs") is List<object> pairs)
            {
                foreach (var prObj in pairs)
                {
                    if (!(prObj is Dictionary<string, object> pr)) continue;
                    var slot = GetVal(pr, "slot") as string ?? "0";
                    var stage = GetVal(pr, "stage") as string ?? "fragment";
                    var viewSlot = GetVal(pr, "view_slot") as string ?? "0";
                    var smpSlot = GetVal(pr, "sampler_slot") as string ?? "0";
                    sb.AppendLine($"                d.texture_sampler_pairs[{slot}].stage = sg_shader_stage.{Stage(stage)};");
                    sb.AppendLine($"                d.texture_sampler_pairs[{slot}].view_slot = {viewSlot};");
                    sb.AppendLine($"                d.texture_sampler_pairs[{slot}].sampler_slot = {smpSlot};");
                }
            }

            sb.AppendLine("                return Gfx.make_shader(&d);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            ctx.AddSource($"Shader_{name}__metal_macos.g.cs", sb.ToString());
        }

        private static string AttrBaseType(string s)
        {
            switch (s)
            {
                case "SInt": return "SG_SHADERATTRBASETYPE_SINT";
                case "UInt": return "SG_SHADERATTRBASETYPE_UINT";
                default: return "SG_SHADERATTRBASETYPE_FLOAT";
            }
        }

        private static string Stage(string s)
        {
            switch (s)
            {
                case "vertex": return "SG_SHADERSTAGE_VERTEX";
                case "compute": return "SG_SHADERSTAGE_COMPUTE";
                default: return "SG_SHADERSTAGE_FRAGMENT";
            }
        }

        private static string ImageType(string s)
        {
            switch (s)
            {
                case "cube": return "SG_IMAGETYPE_CUBE";
                case "3d": return "SG_IMAGETYPE_3D";
                case "array": return "SG_IMAGETYPE_ARRAY";
                default: return "SG_IMAGETYPE_2D";
            }
        }

        private static string SampleType(string s)
        {
            switch (s)
            {
                case "depth": return "SG_IMAGESAMPLETYPE_DEPTH";
                case "sint": return "SG_IMAGESAMPLETYPE_SINT";
                case "uint": return "SG_IMAGESAMPLETYPE_UINT";
                case "unfilterable_float": return "SG_IMAGESAMPLETYPE_UNFILTERABLE_FLOAT";
                default: return "SG_IMAGESAMPLETYPE_FLOAT";
            }
        }

        private static string SamplerType(string s)
        {
            switch (s)
            {
                case "nonfiltering": return "SG_SAMPLERTYPE_NONFILTERING";
                case "comparison": return "SG_SAMPLERTYPE_COMPARISON";
                default: return "SG_SAMPLERTYPE_FILTERING";
            }
        }

        private static object GetVal(Dictionary<string, object> map, string key)
            => map != null && map.TryGetValue(key, out var v) ? v : null;

        private static string FindContent(ImmutableArray<AdditionalText> files, string pathFromYaml, SourceProductionContext ctx)
        {
            if (string.IsNullOrEmpty(pathFromYaml)) return null;
            var fn = Path.GetFileName(pathFromYaml);
            foreach (var f in files)
                if (string.Equals(Path.GetFileName(f.Path), fn, StringComparison.OrdinalIgnoreCase))
                    return f.GetText(ctx.CancellationToken)?.ToString();
            return null;
        }
    }

    /// <summary>std140 layout for the GLSL scalar/vector/mat4 types used by sgp shaders.</summary>
    internal static class Std140
    {
        public static (List<(string Name, string CsType, int Offset, string Glsl, int Size)> members, int size, bool supported) Layout(
            List<(string type, string name, int arr)> members)
        {
            var outm = new List<(string, string, int, string, int)>();
            int offset = 0;
            foreach (var (type, name, arr) in members)
            {
                if (arr > 0) return (outm, 0, false); // arrays unsupported in v1
                if (!Map(type, out var cs, out var sz, out var al, out var glsl)) return (outm, 0, false);
                offset = Align(offset, al);
                outm.Add((name, cs, offset, glsl, sz));
                offset += sz;
            }
            return (outm, Align(offset, 16), true);
        }

        // cs = C# type for the typed struct; glsl = Zinc.GlslType enum name; size = data bytes; align = std140 alignment.
        private static bool Map(string type, out string cs, out int size, out int align, out string glsl)
        {
            switch (type)
            {
                case "float": cs = "float"; size = 4; align = 4; glsl = "Float"; return true;
                case "int": cs = "int"; size = 4; align = 4; glsl = "Int"; return true;
                case "uint": cs = "uint"; size = 4; align = 4; glsl = "UInt"; return true;
                case "bool": cs = "int"; size = 4; align = 4; glsl = "Int"; return true;
                case "vec2": cs = "global::System.Numerics.Vector2"; size = 8; align = 8; glsl = "Vec2"; return true;
                case "vec3": cs = "global::System.Numerics.Vector3"; size = 12; align = 16; glsl = "Vec3"; return true;
                case "vec4": cs = "global::System.Numerics.Vector4"; size = 16; align = 16; glsl = "Vec4"; return true;
                case "mat4":
                case "mat4x4": cs = "global::System.Numerics.Matrix4x4"; size = 64; align = 16; glsl = "Mat4"; return true;
                default: cs = null; size = 0; align = 0; glsl = null; return false;
            }
        }

        private static int Align(int x, int a) => ((x + a - 1) / a) * a;
    }

    /// <summary>
    /// Minimal parser for the fixed, block-style YAML sokol-shdc emits (--format bare_yaml).
    /// Sequence items are always a lone "-" with deeper children; mappings are "key: value"
    /// or "key:" + a deeper block. Not a general YAML implementation.
    /// </summary>
    internal static class MiniYaml
    {
        public static object Parse(string text)
        {
            var lines = new List<(int indent, string content)>();
            foreach (var raw in text.Replace("\r\n", "\n").Split('\n'))
            {
                if (string.IsNullOrWhiteSpace(raw)) continue;
                var trimmed = raw.TrimStart(' ');
                if (trimmed.StartsWith("#")) continue;
                lines.Add((raw.Length - trimmed.Length, trimmed.TrimEnd()));
            }
            int idx = 0;
            if (lines.Count == 0) return null;
            return ParseBlock(lines, ref idx, lines[0].indent);
        }

        private static object ParseBlock(List<(int indent, string content)> lines, ref int idx, int curIndent)
        {
            if (idx >= lines.Count) return null;
            return lines[idx].content == "-"
                ? (object)ParseSeq(lines, ref idx, curIndent)
                : ParseMap(lines, ref idx, curIndent);
        }

        private static List<object> ParseSeq(List<(int indent, string content)> lines, ref int idx, int curIndent)
        {
            var list = new List<object>();
            while (idx < lines.Count && lines[idx].indent == curIndent && lines[idx].content == "-")
            {
                idx++; // consume the "-"
                if (idx < lines.Count && lines[idx].indent > curIndent)
                    list.Add(ParseBlock(lines, ref idx, lines[idx].indent));
                else
                    list.Add(null);
            }
            return list;
        }

        private static Dictionary<string, object> ParseMap(List<(int indent, string content)> lines, ref int idx, int curIndent)
        {
            var map = new Dictionary<string, object>();
            while (idx < lines.Count && lines[idx].indent == curIndent && lines[idx].content != "-")
            {
                var line = lines[idx].content;
                int colon = line.IndexOf(':');
                if (colon < 0) { idx++; continue; }
                var key = line.Substring(0, colon).Trim();
                var val = line.Substring(colon + 1).Trim();
                idx++;
                if (val.Length > 0)
                    map[key] = val;
                else if (idx < lines.Count && lines[idx].indent > curIndent)
                    map[key] = ParseBlock(lines, ref idx, lines[idx].indent);
                else
                    map[key] = null;
            }
            return map;
        }
    }
}
